# permissions for end users to view g2048s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: g2048-viewer-role
rules:
- apiGroups:
  - game.example.com
  resources:
  - g2048s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - game.example.com
  resources:
  - g2048s/status
  verbs:
  - get
