# permissions for end users to edit g2048s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: g2048-editor-role
rules:
- apiGroups:
  - game.example.com
  resources:
  - g2048s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - game.example.com
  resources:
  - g2048s/status
  verbs:
  - get
